server:
  port: 8082

grpc:
  server:
    port: 7071

spring:
  application:
    name: EmployeeService

  datasource:
    url: jdbc:postgresql://localhost:5433/employee_service
    username: employee_user
    password: employee_pass

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: employee-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.roomreservation.notificationservice.messaging.event.InviteEmailFailedFinalEvent:com.roomreservation.employeeservice.messaging.event.InviteEmailFailedFinalEvent
      auto-offset-reset: earliest

jwt:
  secret: "Qm9zYV9zZWN1cmVfSldUX3NlY3JldF9rZXlfNTY3ODkw"

app:
  kafka:
    topics:
      inviteEmailFailed: invite-email.failed

auth-service:
  url: "http://localhost:8081"
  retry:
    max-attempts: 3
    initial-backoff-ms: 200

springdoc:
  default-flat-param-object: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
